<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>EvoSC.Modules.Official.MusicModule</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AssemblyName>MusicModule</AssemblyName>
        <Title>Music Jukebox</Title>
        <Description>A full jukebox module for playing custom music on the server.</Description>
        <Version>1.0.0</Version>
        <Authors>Evo</Authors>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\EvoSC.Modules.SourceGeneration\EvoSC.Modules.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Player\Player.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\EvoSC.Modules\EvoSC.Modules.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Templates\**\*" />
    </ItemGroup>

</Project>
